### ISSUE TITLE
set dynamically css class for rows

### ISSUE THREAD

**Issue by kisakov** [DynamicTyped/Griddle#101]
I need to set dynamically css class for rows if they contains some specific text.
I did it with componentDidUpdate like this:
```
 componentDidUpdate: function(a,b) {
    $(this.getDOMNode()).find(" td span:contains('UD')").parents("tr").addClass("red");
  },
```
But it work's only one, when data loaded into table. And after filter or sort - table refreshing.
What is better way for i?
I need to change only css classes in rows. Not all CustomRowComponent or all events.

Thank you!

**Comment by olethanh** [comment]
I was also looking into it, and it seems the only way would be to copy paste and modify the whole GridRow which kind of seems suboptimal

**Comment by olethanh** [comment]
Poking around the code source I have threes ideas on how to resolve this:

1/ Something like rowMetadata.bodyCssClassName as a function taking 'rowData' as a parameter
2/ rowMetaData taking the name of a field in 'data' to use as the class name (A bit faster than 1/ since it uses less function calls)
3/  Simply use a field _rowClassName if it's present in 'rowData'

I'm willing to work on a PR but would like to know the preferred way to move forward with this before really working on it.

**Comment by joellanciaux** [comment]
As of 0.2.9, we have something in please that's similar to option 1, where one can specify a string _or_ a function to handle setting a row's class.

```javascript
var customRowMetadata = {
  bodyCssClassName: function(rowData) {
    return rowData.orderStatus;
  }
}

React.render(
  <Griddle ... rowMetadata={customRowMetadata} />
)
```

Let me know if that works for you!

Note: We're a bit out of sync on the documentation front, but we're looking to get everything up to date with the 0.3.0 release. :+1:

**Comment by olethanh** [comment]
That seems indeed to fix my problem, Thanks a lot

**Comment by ryanlanciaux** [comment]
Awesome glad to hear that helped! :+1:

**Comment by Debananda** [comment]
Can we have the solution for the same in 1.0 version

**Comment by dahlbyk** [comment]
@Debananda as of https://github.com/GriddleGriddle/Griddle/pull/644 you can specify `cssClassName` as a function to `RowDefinition`:

https://github.com/GriddleGriddle/Griddle/blob/cc296fe16f0c8c2b566bfe3abefce9e1db242348/stories/index.tsx#L409-L414

**Comment by Debananda** [comment]
Thanks @dahlbyk. It working as charm ...
