### ISSUE TITLE
Unexpected token class

### ISSUE THREAD

**Issue by drewhamlett** [DynamicTyped/Griddle#108]
Hi, I updated from 0.2.3 to 0.2.6 in NPM and all the sudden I'm getting the actual source file and not the transpiled code?  Is there something I'm doing wrong.

```js
class ColumnProperties{
  constructor (allColumns = [], filteredColumns=[], childrenColumnName="children", columnMetadata=[], metadataColumns=[]){
    this.allColumns = allColumns;
    this.filteredColumns = filteredColumns;
    this.childrenColumnName = childrenColumnName;
    this.columnMetadata = columnMetadata;
    this.metadataColumns = metadataColumns;
  }
```

I don't have a single vendor dependency that I have to perform a JSX transform on.

**Comment by ryanlanciaux** [comment]
Hi there - really really sorry about that. Using 0.2.7 should resolve.
