### ISSUE TITLE
Remove @jsx React.DOM

### ISSUE THREAD

**Issue by kentcdodds** [DynamicTyped/Griddle#109]
Because Griddle's `peerDependency` for react is >= 0.12.x, we can get rid of the `/** @jsx React.DOM */` note on both the `customRowComponentContainer.jsx.js` as well as the `customPaginationContainer.jsx.js` files. Sooner the better because `babel` will throw an error because the pragma has been deprecated as of React 0.12.

**Comment by ryanlanciaux** [comment]
Thanks so much! Please let us know of anything else you encounter :+1:
