### ISSUE TITLE
Missing Columns

### ISSUE THREAD

**Issue by jehoshua02** [DynamicTyped/Griddle#110]
We ran into a case where we are specifying columns, but if the key is missing in the data, we don't get the <td> we are expecting.

Reproduce:

1. Open our example http://reactweek.com/projects/reactTunes/
2. Search for "a" and click Submit.

**Comment by ryanlanciaux** [comment]
I wonder if you're encountering what @saary fixed [here](https://github.com/DynamicTyped/Griddle/pull/102). If that's the case, I think upgrading to griddle-react 0.2.7 may resolve. Please let us know if that fixes it for you. :+1:

**Comment by jehoshua02** [comment]
That's probably it. I'll try in the morning and let you know.

On Tuesday, March 10, 2015, Ryan Lanciaux <notifications@github.com> wrote:

> I wonder if you're encountering what @saary <https://github.com/saary>
> fixed here <https://github.com/DynamicTyped/Griddle/pull/102>. If that's
> the case, I think upgrading to griddle-react 0.2.7 may resolve. Please let
> us know if that fixes it for you. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DynamicTyped/Griddle/issues/110#issuecomment-78199328>
> .
>


-- 


Joshua K Stoutenburg
Web Applications Developer
jehoshua02@gmail.com
503-916-9945

**Comment by jwarkentin** [comment]
I just tested and I can confirm that the update to 0.2.7 fixes this issue.

**Comment by jehoshua02** [comment]
Sweet

On Tuesday, March 10, 2015, Justin Warkentin <notifications@github.com>
wrote:

> I just tested and I can confirm that the update to 0.2.7 fixes this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DynamicTyped/Griddle/issues/110#issuecomment-78206882>
> .
>


-- 


Joshua K Stoutenburg
Web Applications Developer
jehoshua02@gmail.com
503-916-9945

**Comment by THPubs** [comment]
Hi, I'm facing this same issue. Any idea what's happening?
