### ISSUE TITLE
Issue updating table results from ajax, and incorrect example

### ISSUE THREAD

**Issue by decodeman** [DynamicTyped/Griddle#14]
Hi, thanks for your component.  Is there any way Griddle could render results more than once, so we can follow React examples and simply make the ajax call ourselves when our component mounts and then update our setState() thereby passing updated 'results' property to your Griddle component?

1) Currently when I try this (and let's say I even try to poll the server for new results every X seconds), Griddle will not re-render (as I see in the code it only cares about props.results in the original getInitialState call.

This is the basic code I'd like to be able to work with Griddle, which follow React examples of how to do things
```javascript
var MusingsSearchResults = React.createClass({
  getInitialState: function() {
    return {musings: []};
  },
  componentDidMount: function() {
    this.loadMusingsFromServer(); //doesn't work out, because Griddle 'results' property must be populated ahead of time
    setInterval(this.loadMusingsFromServer,5000); //could even try to poll
  },
  loadMusingsFromServer: function() {
    debugger;
    $.ajax({
      url: 'musings.json',
      dataType: 'json',
      success: function(data) {
        this.setState({musings: data});
      }.bind(this),
      error: function(xhr, status,err) {
        console.error(xhr, status, err.toString());
      }.bind(this)
    });    
  },
  render: function() {
    return <Griddle results={this.state.musings} tableClassName="table"/>;
  }  
});
```
2) I do see getExternalResults, though I don't need paging or filter... just ability to easily feed results from my ajax call (which I may want to poll every X seconds).  I did notice this fyi: I think the callback example at http://dynamictyped.github.io/Griddle/ is not supposed to pass a function, just the results and totalResults? 
```javascript
var fakeDataMethod = function(filterString, sortColumn, sortAscending, page, pageSize, callback) {
	// Load results from your API here.
	callback(function() {
		results: [],
		totalResults: 300
	});
}
```
For example, this works for me:
```javascript
  loadItUp: function(filterString, sortColumn, sortAscending, page, pageSize, callback) {
    $.ajax({
      url: 'musings.json',
      dataType: 'json',
      success: function(data) {
        callback({
          results: data,
          totalResults: data.length
        });
      }.bind(this),
      error: function(xhr, status,err) {
        console.error(xhr, status, err.toString());
      }.bind(this)
    });    
  },  
  render: function() {
    //return <Griddle results={this.state.musings} tableClassName="table"/>;
    return <Griddle getExternalResults={this.loadItUp} tableClassName="table"/>;
  }  
```

Thanks again! (Note maybe I have React misunderstood, but I think components' render should be able to handle props updates. And I can't think of how to call render the very first time with async ajax callback data already provided.)

-First time poster on GitHub (unsure how to find responses, so I'll check back for issue comments)

**Comment by ryanlanciaux** [comment]
I'm closing this out as the ver0.2.0 release should have made this sort of thing a bit easier. [The  external data documentation](http://dynamictyped.github.io/Griddle/externalData.html) contains some better example than the original docs. Please feel free to ping me if this is still giving you trouble! :+1:
