### ISSUE TITLE
Why thead and tbody in different tables?

### ISSUE THREAD

**Issue by e-kolkhoz** [DynamicTyped/Griddle#40]
Why thead and tbody in different tables?
![7](https://cloud.githubusercontent.com/assets/9208205/5528278/5f50c90e-8a17-11e4-95fe-e55243f7d63c.png)

What should I do if I don't want have sorting by clicking on headers, but want to have correct width of all columns in tbody and theader?

**Comment by ryanlanciaux** [comment]
Hi @e-kolkhoz, ver 0.2.0 is the latest version -- Griddle, by default, now renders as a single table. Please feel free to open this back up if it is still giving you grief. :+1:
