### ISSUE TITLE
GriddleWithCallback from ver0.2.0

### ISSUE THREAD

**Issue by 0xdabbad00** [DynamicTyped/Griddle#41]
In order to use the `ver0.2.0` branch with the `GriddleWithCallback` component, I needed to edit `package.json` to use the line:  `"main": "./modules/main.js",`
Then I created the `./modules/main.js` file with the contents:

```
module.exports = {
  Griddle: require('./Griddle.jsx.js'),
  GriddleWithCallback: require('./GriddleWithCallback.jsx.js')
};
```

I tried using the `GriddleWithCallback` component as shown in `index2.html` but it is missing many of the original variables of a normal `Griddle` component, such as being able to set `showFilter` to `false`.

**Comment by ryanlanciaux** [comment]
I really appreciate that you're looking into this! I just noticed there were some properties that were hardcoded in the Griddle call (showFilter and showSettings, for instance) in griddleWithCallback.render which would prevent properties from being anything but true. At some point, could you please try again with the build/griddleWithCallback.js file? I *think* it will be a slightly better outcome this time. :) 

See [this changeset](https://github.com/DynamicTyped/Griddle/commit/124da8f6eb1a7144bff4be135810743b1dfadfe4) for more info.

**Comment by ryanlanciaux** [comment]
Could you take a look at this again at some point and let us know if this is still causing issues in the 0.2.x release? :+1:
