### ISSUE TITLE
Loading message

### ISSUE THREAD

**Issue by 0xdabbad00** [DynamicTyped/Griddle#42]
Using the current (master) branch, I am able to choose a `noDataMessage` message.  This message is displayed both while data is being loaded (if my server takes a long time to supply the external results), and if there are actually no results.  So I'm stuck having to decide to use "Loading..." or "No data available" as my `noDataMessage`.  I think this may be fixed in `ver0.2.0` via `loadingComponent`, but I just want to ensure that will be possible then.

**Comment by ryanlanciaux** [comment]
Thank you for reporting this! This will be something that we will make sure to test before the final 0.2.0 is released :)

**Comment by ryanlanciaux** [comment]
Sorry about the delay on this one. Please follow-up if you're still seeing anything like this :+1:
