### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by cesarandreu** [DynamicTyped/Griddle#46]
Right now there's 0.1.19 and 0.1.18, would you consider tagging them? Thanks!

**Comment by ryanlanciaux** [comment]
Hey thanks for posting! I've added the tagged versions. [v0.1.18](https://github.com/DynamicTyped/Griddle/releases/tag/v0.1.18) and [v0.1.19](https://github.com/DynamicTyped/Griddle/releases/tag/v0.1.19). :+1:

**Comment by cesarandreu** [comment]
Thanks! I appreciate it.
