### ISSUE TITLE
Toolbar and make it possible to select rows

### ISSUE THREAD

**Issue by NotSureAbout** [DynamicTyped/Griddle#48]
I think it would be a nice feature if the grid had a tool bar and allowed the users to select rows.

**Comment by matiit** [comment]
What do you mean by toolbar? What would be the purpose?

**Comment by ryanlanciaux** [comment]
@NotSureAbout Thanks for suggesting a feature. Could you please give an example of what you're thinking? :+1:

**Comment by ryanlanciaux** [comment]
Hey @NotSureAbout I'm going to close this for now. I don't know that a toolbar is in the list of features that we are planning to add but if it's something you need on your project, you can wrap griddle in another component and define Griddle with a ref and interact with the methods that way. Please be sure to let us know if you're having any trouble with this :+1:
