### ISSUE TITLE
Changing state results does not update the table.

### ISSUE THREAD

**Issue by appsciences** [DynamicTyped/Griddle#49]
Storing results in state and then changing state doesn't seem to update the table, as in:

    var TestTable = React.createClass({...
    getInitialState: function() {
        return {
            test: [{name:"foo"}]
        };
    },

    test: function(event) {
        this.setState(
            {test: [{name:"bar"}]}
        );
    },

    render: function() {
        return (
        <Griddle
            results={this.state.test}
        />
        <button onChange="this.test">
    )})}

**Comment by ryanlanciaux** [comment]
Hi there! We just updated Griddle to ver 0.2.0 and this behavior should be a bit easier now. If the end result is you'd like to wrap up an API call or something along those lines, please check out [the External Data section](http://dynamictyped.github.io/Griddle/externalData.html) on the updated documentation and let me know if it's still causing problems.

**Comment by ryanlanciaux** [comment]
Just checking in -- were you able to figure this out? I've tossed an [example of this scenario in jsfiddle](http://jsfiddle.net/m9hyhwra/3/) (mostly using the code you provided). I'm closing this out for now but please let me know if you have any trouble! :+1:
