### ISSUE TITLE
Setting column visibility has no effect

### ISSUE THREAD

**Issue by lostman** [DynamicTyped/Griddle#54]
When I try the following:

```
React.render(React.createElement(Griddle, {columnMetadata: [{order: 2, columnName: "foo", visible: true, displayName: "FOO"}, {order: 1, columnName: "bar", visible: false, displayName: "BAR"}], results: [{foo: "foo", bar: "bar"}, {foo: "123", bar: "456"}]}), document.body)
```

`displayName` and `order` attributes are respected but `visible` is ignored.

**Comment by ryanlanciaux** [comment]
This is an issue we hope to have ironed out in the 0.2.1 release. Thanks! :+1:

**Comment by ryanlanciaux** [comment]
Thanks again for reporting this! Please let us know if you're still seeing anything like this.
