### ISSUE TITLE
Replace underscore dependency with lodash custom build

### ISSUE THREAD

**Issue by moklick** [DynamicTyped/Griddle#56]
Did you consider to replace underscore with a custom Lo-Dash build in order to reduce the size of your component?

* [Custom Lo-Dash builds](https://lodash.com/custom-builds)
* [Lo-Dash functions as npm packages](https://www.npmjs.com/browse/keyword/lodash-modularized)

**Comment by ryanlanciaux** [comment]
Thanks for posting this suggestion! We have been considering ways to remove the dependency on underscore but haven't made too much progress on that yet. Lo-Dash seems like it could fit the bill nicely. 

The other idea that we are kicking around is to see if we can get by with using only the new ES6 features instead of using a library. It would be ideal to have Griddle depend only on React but we'll see how that works out. Any thoughts on this approach?

**Comment by moklick** [comment]
I think ES6 does not help you here. Replacing underscore with a Lo-Dash build that only contains the methods you are using would be very simple. You just have to make a custom build and replace `var _ = require('underscore')` with `var _ = require('lodash')`. It's the same API.

**Comment by scvnc** [comment]
One thing to note is that Griddle's webpack is currently configured to externalize underscore so the user could choose whether they want to use underscore or lodash by including the CDN in their app.  Webpack more or less makes it so `require('underscore') == window._`.  No code changes necessary and reap the benefits of lodash.

If you're looking to squeeze those kb then the you could build your own lodash build and package it with your app.

This little bash script produces a ~6kb lodash subset and it seems to work fine against the Griddle docs

    # depends on: npm install -g lodash-cli

    # Search through all source producing comma delimited lodash functions
    usedFuncs=$(
        grep -ohPr '_\.[a-zA-Z0-9]+' scripts | 
        cut -d. -f2 | 
        sort -u | 
        tr "\\n" ",")

    lodash include=${usedFuncs}

Perhaps this could eventually be part of the build process of Griddle in some shape but I think this sort of tuning should be left up to the user. What if I'm using lodash in my app and there's overlap? I may end up having some lodash funcs included twice in my bundle.

**Comment by ryanlanciaux** [comment]
@scvnc That is a very slick script and thanks for trying that against the Griddle docs! 

@moklick You are dead-on that by default ES6 doesn't serve as a replacement to underscore/lodash :+1: . I should have worded what I meant a little more clearly -- I am looking into what it would take to replace the underscore methods with functions written specifically for those tasks. It seems that using ES6 would make this easier, however, it's not something I want to approach too quickly. Both underscore and lodash are pretty solid. 

I think using lodash is a great suggestion and that may make its way into a future version :+1: . I will go ahead and close this for now. Please follow up if the suggestion @scvnc suggested doesn't work out for you.
