### ISSUE TITLE
Toggling visibility in Settings removes the value from rowData

### ISSUE THREAD

**Issue by lostman** [DynamicTyped/Griddle#57]
Small example:
```
React.render(
    React.createElement(Griddle,
        {showSettings: true
        , columnMetadata: [
                {columnName: "foo"
                , "visible": true
                , customComponent: React.createClass({
                        render: function() {
                                return React.createElement("div", null, "foo: ", this.props.data, " bar: ", this.props.rowData.bar);
                        }})}
                , {columnName: "bar"
                , "visible": true}]
        , results: [{foo: "foo", bar: "bar"}]})
        , document.body)
```

Column `foo` contains the value `foo: foo bar: bar`. Now go to Settings and hide `bar`. Back in foo we see `foo: foo bar:`. That is, the value `this.props.rowData.bar` is no longer available.

The first thing I tried with Griddle was displaying objects where to fields in the object combine into one display cell. Hence I found this.

**Comment by ryanlanciaux** [comment]
Thanks for reporting and for including an example! I think we'll have to do something to pass the hidden columns through to custom components as well. 

We are hoping to have a version 0.2.1 out within the next week, which should contain a fix.
