### ISSUE TITLE
Setting "visible" to false in metadata object removes it from rowData

### ISSUE THREAD

**Issue by zsherman** [DynamicTyped/Griddle#63]
You should still be able to access the attributes if the visibility is set to valse.

**Comment by mattmccray** [comment]
In fact, shouldn't you have access to all the row data in `rowData`, not just the visible columns? 

How else do you create a composite cell (example: A 'Name' cell that just concats `firstName` and `lastName` from the `rowData`)?

**Comment by ryanlanciaux** [comment]
Thanks for posting the info :+1: This issue is now fixed in the repository but not yet reflected in npm. 

I'm going to close this one for now but please feel free to follow up on #57 if you're still seeing anything not working quite right.

**Comment by zsherman** [comment]
Awesome, thanks Ryan - any idea of when npm will be updated?

**Comment by ryanlanciaux** [comment]
No problem :+1: I just updated npm to 0.2.4 which is basically just this fix :)
