### ISSUE TITLE
Remove 'row' class from filter-container when using useGriddleStyles=false

### ISSUE THREAD

**Issue by nlien** [DynamicTyped/Griddle#67]
The 'row' class that is added to the GridFilter's rendered element is unfortunate IMHO. In my case, I use Bootstrap as CSS framework, and the 'row' class is part of Bootstrap's grid system. Having this class on the filter-container will therefore conflict with my grid-setup.

This class ought to not be there when using useGriddleStyles=false, in my opinion.

I have dealt with this temporarily by manually removing the class upon component mount:
```javascript
    componentDidMount: function () {
      $(this.getDOMNode()).find('.filter-container').removeClass('row');
    }
```

**Comment by ryanlanciaux** [comment]
Thanks for reporting this! You are correct that this is not an ideal class to use here :) -- it may be something we missed when we removed bootstrap as a dependency. We will change it in the near future :+1:

**Comment by danawoodman** [comment]
It would be great if all CSS classes could be overridden, including the above mentioned issue. Is there a way to modify the table header component/CSS?
