### ISSUE TITLE
Example not working in Chrome with dev tools open - Uncaught TypeError: Cannot read property 'componentWillUpdate' of null 

### ISSUE THREAD

**Issue by ettysekhon** [DynamicTyped/Griddle#68]
In the example shown http://dynamictyped.github.io/Griddle/ when you open the dev tools in chrome and enter something in the filter you see error Uncaught TypeError: Cannot read property 'componentWillUpdate' of null 

![react-griddle-error](https://cloud.githubusercontent.com/assets/389055/5999324/a7edb25e-aac8-11e4-9e94-32e952704154.png)

**Comment by ryanlanciaux** [comment]
Thanks for reporting this! Unfortunately, I am unable to reproduce this on the docs site or running locally (tried on both Windows and Mac). Is this on the docs site that you're encountering this or running from grunt on the repository? What version of Chrome are you seeing this on? Any other information that you can think of would be helpful too -- I appreciate it :+1:

**Comment by ettysekhon** [comment]
Hi Ryan, I'm encountering this on the docs site using chrome version "35.0.1916.153 m" on windows 7. I'll see if i can re-create the bug on my mac with latest version of chrome.

**Comment by ettysekhon** [comment]
Hi Ryan, I've identified the issue, the issue is linked to the React Developer Tools plugin for Chrome! which does not work with older version of Chrome I have at work; for some reason it generates this error when I have the dev tools open on a site using react. I'll close the issue. Thanks Etty

**Comment by ryanlanciaux** [comment]
@ettysekhon Thanks so much for tracking this down! I'm glad you've figured it out! :+1:
