### ISSUE TITLE
add a class to no-data GridNoData?

### ISSUE THREAD

**Issue by fraserxu** [DynamicTyped/Griddle#69]
Thanks for this amazing component!

I've been using this in my project, but in some case there might be no data available in the table.

The `GridNoData` component seems handy but unfortunately there's no way I could style it, so I was thinking if we could add something like `no-data` class to the `div`?

**Comment by fraserxu** [comment]
Sorry, just found out  there's an `customNoDataComponent`, which could solve my problem. 

But it might still be helpful if there's a className on it. :D

**Comment by ryanlanciaux** [comment]
Hey @fraserxu. Thanks so much for checking out Griddle - I'm glad you're liking it! It would be a good idea to have the class instead of just the custom component. We'll try to get that in the next version! :+1:

**Comment by fraserxu** [comment]
Hi @ryanlanciaux , Thanks for the update.

But after installing the latest version(0.2.4), seems that the code you pushed here is not in the npm module files.

Can you check?

**Comment by QRCharlie** [comment]
It seems the GridNoData class does not receive the className prop at all. 
No class reference appears in modules/gridNoData.jsx.js file.

Version 0.6.1
