### ISSUE TITLE
Grid table header class not working

### ISSUE THREAD

**Issue by danawoodman** [DynamicTyped/Griddle#70]
It appears that the reference to `this.titleStyles` in the `gridTitle.jsx` file is not defined:
https://github.com/DynamicTyped/Griddle/blob/abd9319aa1bbab8c3edca0073dbb00c4a7e18858/scripts/gridTitle.jsx#L82

I'm wondering if this was intended to be a prop or possibly a computed value that just was never set. Right now it's just set to `class="undefined"` once rendered.

My proposal would be to create a `tableHeaderClassName` prop that can be passed into `<Griddle>` so that we are able to override the default table header row class. Perhaps also a `tableHeaderStyles` as well for those that like inline styles.

**Comment by danawoodman** [comment]
Depending on what you'd like to do, I may have the bandwidth to implement this as I need it for a current client project.

**Comment by ryanlanciaux** [comment]
Thanks for taking a stab at this! I am sorry about the delay in taking a look at these requests but hopefully this weekend I'll some time to check them out! :+1:

**Comment by danawoodman** [comment]
@ryanlanciaux no worries, would be great to get them merged in soon as I've got a few more improvements I was hoping to make that depend on these changes.
